### PR TITLE
Handle empty size

### LINKED ISSUE #25: When size is empty, emoji link is broken
## Problem
For example, if we define `svgEmoji()` with `size: ''`,
this will outputs `https://twemoji.maxcdn.com/2/svg//1f600.svg`.

(Expected output: `https://twemoji.maxcdn.com/2/svg/1f600.svg`)

```js
function svgEmoji (input) {
	return emoji(input, {
		baseUrl: 'https://twemoji.maxcdn.com/2/svg/',
		ext: '.svg',
		size: ''
	})
}
```

## Cause
When `options.baseUrl` ends with `/` and `options.size` is empty, the library should remove `/` from `options.baseUrl`

https://github.com/appfigures/react-easy-emoji/blob/e6c3949416838fdf2dfebca98e625cbbd6ae99c5/lib/makeTwemojiRenderer.js#L29-L35

### PR DESCRIPTION
**Pull request by pdx-daniel**
- Fixes #25 , where empty size strings produced invalid twemoji urls
- Adds a unit test for the above issue
- Adds a unit test for emoji 14 support

### CODE REVIEW

**Review by robinsoncol — APPROVED** [review]

File: lib/makeTwemojiRenderer.js [hunk 1]
```diff
@@ -60,4 +53,25 @@ function merge() {
...
+function getSource(options, icon){
+	var source = ''
+
+	if (options.baseUrl.indexOf('http') !== 0) {
+		source += normalizeProtocol(options.protocol)
+	}
+
+	source += options.baseUrl
+
+	if(options.size === '' && options.baseUrl.endsWith('/') && options.ext === '.svg'){
```
Comment (oztune) [inline lib/makeTwemojiRenderer.js]: I think adding svg to the url should be more explicit, and not an implicit behavior from passing `size: ''`. So I think a more robust solution for better svg support would require a larger API change. We're also very sensitive to the bundle size so I'd suggest a simpler fix of simply dropping the double slash with minimal modifications to line 36. This way our existing API would work more as expected, but would still require the users to modify the base url to add `/svg`.

Another consideration is: would making this change break the issue reporter's existing bug fix https://github.com/line/armeria/pull/4646/files#diff-2f901e80d43fc4fbadc238e158e1f4f161fbc9baf23d030dfa4e331a1b0e3b0c

**Review by oztune — CHANGES_REQUESTED** [review]

**Comment by oztune** [comment]
After some discussion we think the right solution is to:
- If a size wasn't provided by the user (either null or empty string), don't include the size component in the url at all (to avoid the `//`)
- If the base url doesn't have a trailing slash we'll insert it

File: lib/makeTwemojiRenderer.js [hunk 2]
```diff
@@ -60,4 +53,29 @@ function merge() {
...
+}
+
+function getSource(options, icon){
+	var source = ''
+
+	if (options.baseUrl.indexOf('http') !== 0) {
+		source += normalizeProtocol(options.protocol)
+	}
+
+	var baseUrl = options.baseUrl.endsWith('/') ? options.baseUrl : options.baseUrl + '/'
```
Comment (oztune) [inline lib/makeTwemojiRenderer.js]: We shouldn't use endsWith as it would break with older browsers

File: lib/makeTwemojiRenderer.js [hunk 3]
```diff
@@ -60,4 +53,29 @@ function merge() {
...
+
+	source += baseUrl
+
+	if(options.size === '' || options.size == null){
+		if(options.ext === '.svg'){
+			//Handle https://github.com/appfigures/react-easy-emoji/issues/25
+			source += 'svg/'
```
Comment (oztune) [inline lib/makeTwemojiRenderer.js]: Instead of injecting this into the path, we should let the user manage it through the `baseUrl` param as the project README shows

File: lib/makeTwemojiRenderer.js [hunk 4]
```diff
@@ -60,4 +53,29 @@ function merge() {
 		}
    }
    return out
+}
+
+function getSource(options, icon){
```
Comment (oztune) [inline lib/makeTwemojiRenderer.js]: We should fold this function back into renderTwemoji, since the only change that needs to happen is on line 35

**Review by oztune — CHANGES_REQUESTED** [review]

File: lib/makeTwemojiRenderer.js (hunk 2 above)
Comment (pdx-daniel) [reply lib/makeTwemojiRenderer.js]: https://github.com/appfigures/react-easy-emoji/pull/26/commits/480e477ead4cde8b3226d5bb1f3c8b497f3440a6

File: lib/makeTwemojiRenderer.js (hunk 3 above)
Comment (pdx-daniel) [reply lib/makeTwemojiRenderer.js]: https://github.com/appfigures/react-easy-emoji/pull/26/commits/dec646eb76faaf4e3d0ba73546f647b4ee3c7856

File: lib/makeTwemojiRenderer.js (hunk 4 above)
Comment (pdx-daniel) [reply lib/makeTwemojiRenderer.js]: https://github.com/appfigures/react-easy-emoji/pull/26/commits/167ab40e66d47faf4c5e1005c9488bc78ae765f6
